version: '2'

services:
  solr:
    container_name: solr
    image: 282251075226.dkr.ecr.eu-west-1.amazonaws.com/apacs-solr:{image-tag}
    ports: 
      - "80:8983"
    volumes:
        - solr-data:/var/solr
    mem_limit: 1024m
    command: solr-precreate apacs_core /opt/solr/server/solr/configsets/apacs-config
  indexer:
    container_name: indexer
    image: 282251075226.dkr.ecr.eu-west-1.amazonaws.com/apacs-indexer:{image-tag}
volumes:
  solr-data: