FROM python:3

WORKDIR /usr/src/app

# Install cron
RUN apt-get update
RUN apt-get install -y cron

# Install requirements
COPY ./indexing/ ./
RUN pip install --no-cache-dir -r requirements.txt

RUN crontab /usr/src/app/crontab
RUN chmod +x ./cron.sh
ENTRYPOINT echo "Indexer started at:" && date && cron && tail -f /dev/null